<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class UsersTableSeeder extends Seeder {
    public function run(){
        DB::table('users')->insert(array(
            array(//'id'=>1,
                'name'=>'admin',
                'password'=>Hash::make('admin'),
                'email'=>"admin@example.com",
                'phone_number'=>'123456789',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
            array(//'id'=>2,
                'name'=>'courier',
                'password'=>Hash::make('courier'),
                'email'=>"courier@example.com",
                'phone_number'=>'987654321',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
            array(//'id'=>3,
                'name'=>'Michał',
                'password'=>Hash::make('AtXBJS'),
                'email'=>"micsob006@utp.edu.pl",
                'phone_number'=>null,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
            array(//'id'=>4,
                'name'=>'Agnieszka',
                'password'=>Hash::make('bUnkpj'),
                'email'=>"agnieszka@example.com",
                'phone_number'=>null,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
            array(//'id'=>5,
                'name'=>'Halina',
                'password'=>Hash::make('FGEagP'),
                'email'=>"halina@example.com",
                'phone_number'=>null,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
            array(//'id'=>6,
                'name'=>'Grzegorz',
                'password'=>Hash::make('e8kMgc'),
                'email'=>"grzegorz@example.com",
                'phone_number'=>null,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
            array(//'id'=>7,
                'name'=>'Amadeusz',
                'password'=>Hash::make('4BhUgW'),
                'email'=>"amadeusz@example.com",
                'phone_number'=>null,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
            array(//'id'=>8,
                'name'=>'Błażej',
                'password'=>Hash::make('yRgmA6'),
                'email'=>"błażej@example.com",
                'phone_number'=>null,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
            array(//'id'=>9,
                'name'=>'Justyn',
                'password'=>Hash::make('4BXsC8'),
                'email'=>"justyn@example.com",
                'phone_number'=>null,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()),
        ));
    }
}
